language: ruby
rvm:
  - 2.7.0
bundler_args: --jobs=2
script:
  - bundle install --jobs=3 --retry=3 --deployment
  - bundle exec rake db:setup
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "12.1"